### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by Blagodarenko** [rico666/cg_obup#1]
https://github.com/rico666/cg_obup/blob/master/plot.c#L82
it will be bit faster if you change to 
before loop: `avx1_mshabal_init(&init_x, 256);`
in loop: `memcpy(&x, &init_x, sizeof(init_x));`

**Comment by rico666** [comment]
done as per
https://github.com/rico666/cg_obup/commit/23d26cb76e6855151171127db8ee904d65ef5d7b
